name: Build and Publish JupyterBook

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install jupyter-book ghp-import
        # pip install -r book/requirements.txt   # if you have one


    - name: Check required files
      run: |
        test -f _config.yml
        test -f _toc.yml
        test -f README.md



    - name: Build Jupyter Book
      run: |
        pwd
        ls
        jupyter-book build . --verbose
        ls

    - name: Publish to GitHub Pages
      run: |
        ghp-import -n -p -f _build/html
